/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 new/tarot.gltf 
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("new/tarot.gltf");
  const [card, setCard] = useState("");
  function handleCard(value) {
    setCard(value);
  }
  return (
    <group {...props} dispose={null}>
      <mesh
        onClick={() => {
          handleCard("The_Fool");
        }}
        geometry={nodes["0_The_Fool_1"].geometry}
        material={materials.Side}
      />
      <mesh
        geometry={nodes["0_The_Fool"].geometry}
        material={materials["0-TheFool"]}
      />
      <mesh
        onClick={() => {
          handleCard("TheMagician");
        }}
        geometry={nodes["1_The_Magician"].geometry}
        material={materials["1-TheMagician"]}
      />
      <mesh
        onClick={() => {
          handleCard("TheHighPriestess");
        }}
        geometry={nodes["2_The_High_Priestess"].geometry}
        material={materials["2-TheHighPriestess"]}
      />
      <mesh
        onClick={() => {
          handleCard("TheEmpress");
        }}
        geometry={nodes["3_The_Empress"].geometry}
        material={materials["3-TheEmpress"]}
      />
      <mesh
        onClick={() => {
          handleCard("TheEmperor");
        }}
        geometry={nodes["4_The_Emperor"].geometry}
        material={materials["4-TheEmperor"]}
      />
      <mesh
        onClick={() => {
          handleCard("TheHierophant");
        }}
        geometry={nodes["5_The_Hierophant"].geometry}
        material={materials["5-TheHierophant"]}
      />
      <mesh
        onClick={() => {
          handleCard("TheLovers");
        }}
        geometry={nodes["6_The_Lovers"].geometry}
        material={materials["6-TheLovers"]}
      />
      <mesh
        onClick={() => {
          handleCard("TheChariot");
        }}
        geometry={nodes["7_The_Chariot"].geometry}
        material={materials["7-TheChariot"]}
      />
      <mesh
        onClick={() => {
          handleCard("Strength");
        }}
        geometry={nodes["8_Strength"].geometry}
        material={materials["8-Strength"]}
      />
      <mesh
        onClick={() => {
          handleCard("TheHermit");
        }}
        geometry={nodes["9_The_Hermit"].geometry}
        material={materials["9-TheHermit"]}
      />
      <mesh
        onClick={() => {
          handleCard("Wheel Of Fortun");
        }}
        geometry={nodes["10_Wheel_of_Fortune"].geometry}
        material={materials["10-WheelOfFortune"]}
      />
      <mesh
        onClick={() => {
          handleCard("Justice");
        }}
        geometry={nodes["11_Justice"].geometry}
        material={materials["11-Justice"]}
      />
      <mesh
        onClick={() => {
          handleCard("TheHangedMan");
        }}
        geometry={nodes["12_The_Hanged_Man"].geometry}
        material={materials["12-TheHangedMan"]}
      />
      <mesh
        onClick={() => {
          handleCard("Death");
        }}
        geometry={nodes["13_Death"].geometry}
        material={materials["13-Death"]}
      />
      <mesh
        onClick={() => {
          handleCard("Temperance");
        }}
        geometry={nodes["14_Temperance"].geometry}
        material={materials["14-Temperance"]}
      />
      <mesh
        onClick={() => {
          handleCard("TheDevil");
        }}
        geometry={nodes["15_The_Devil"].geometry}
        material={materials["15-TheDevil"]}
      />
      <mesh
        onClick={() => {
          handleCard("TheTower");
        }}
        geometry={nodes["16_The_Tower"].geometry}
        material={materials["16-TheTower"]}
      />
      <mesh
        onClick={() => {
          handleCard("TheStar");
        }}
        geometry={nodes["17_The_Star"].geometry}
        material={materials["17-TheStar"]}
      />
      <mesh
        onClick={() => {
          handleCard("TheMoon");
        }}
        geometry={nodes["18_The_Moon"].geometry}
        material={materials["18-TheMoon"]}
      />
      <mesh
        onClick={() => {
          handleCard("TheSun");
        }}
        geometry={nodes["19_The_Sun"].geometry}
        material={materials["19-TheSun"]}
      />
      <mesh
        onClick={() => {
          handleCard("Judgement");
        }}
        geometry={nodes["20_Judgement"].geometry}
        material={materials["20-Judgement"]}
      />
      <mesh
        onClick={() => {
          handleCard("TheWorld");
        }}
        geometry={nodes["21_The_World"].geometry}
        material={materials["21-TheWorld"]}
      />
      <mesh
        onClick={() => {
          handleCard("Wands-King");
        }}
        geometry={nodes.Wands_King.geometry}
        material={materials["Wands-King"]}
      />
      <mesh
        onClick={() => {
          handleCard("Wands-Queen");
        }}
        geometry={nodes.Wands_Queen.geometry}
        material={materials["Wands-Queen"]}
      />
      <mesh
        onClick={() => {
          handleCard("Wands-Knight");
        }}
        geometry={nodes.Wands_Knight.geometry}
        material={materials["Wands-Knight"]}
      />
      <mesh
        onClick={() => {
          handleCard("Wands-Page");
        }}
        geometry={nodes.Wands_Page.geometry}
        material={materials["Wands-Page"]}
      />
      <mesh
        onClick={() => {
          handleCard("Wands-Ace");
        }}
        geometry={nodes.Wands_Ace.geometry}
        material={materials["Wands-Ace"]}
      />
      <mesh
        onClick={() => {
          handleCard("Wands-2");
        }}
        geometry={nodes.Wands_2.geometry}
        material={materials["Wands-2"]}
      />
      <mesh
        onClick={() => {
          handleCard("Wands-3");
        }}
        geometry={nodes.Wands_3.geometry}
        material={materials["Wands-3"]}
      />
      <mesh
        onClick={() => {
          handleCard("Wands-4");
        }}
        geometry={nodes.Wands_4.geometry}
        material={materials["Wands-4"]}
      />
      <mesh
        onClick={() => {
          handleCard("Wands-5");
        }}
        geometry={nodes.Wands_5.geometry}
        material={materials["Wands-5"]}
      />
      <mesh
        onClick={() => {
          handleCard("Wands-6");
        }}
        geometry={nodes.Wands_6.geometry}
        material={materials["Wands-6"]}
      />
      <mesh
        onClick={() => {
          handleCard("Wands-7");
        }}
        geometry={nodes.Wands_7.geometry}
        material={materials["Wands-7"]}
      />
      <mesh
        onClick={() => {
          handleCard("Wands-8");
        }}
        geometry={nodes.Wands_8.geometry}
        material={materials["Wands-8"]}
      />
      <mesh
        onClick={() => {
          handleCard("Wands-9");
        }}
        geometry={nodes.Wands_9.geometry}
        material={materials["Wands-9"]}
      />
      <mesh
        onClick={() => {
          handleCard("Wands-10");
        }}
        geometry={nodes.Wands_10.geometry}
        material={materials["Wands-10"]}
      />
      <mesh
        onClick={() => {
          handleCard("The_Fool");
        }}
        geometry={nodes.Cups_King.geometry}
        material={materials["Cups-King"]}
      />
      <mesh
        onClick={() => {
          handleCard("The_Fool");
        }}
        geometry={nodes.Cups_Queen.geometry}
        material={materials["Cups-Queen"]}
      />
      <mesh
        onClick={() => {
          handleCard("The_Fool");
        }}
        geometry={nodes.Cups_Knight.geometry}
        material={materials["Cups-Knight"]}
      />
      <mesh
        onClick={() => {
          handleCard("The_Fool");
        }}
        geometry={nodes.Cups_Page.geometry}
        material={materials["Cups-Page"]}
      />
      <mesh
        onClick={() => {
          handleCard("The_Fool");
        }}
        geometry={nodes.Cups_Ace.geometry}
        material={materials["Cups-Ace"]}
      />
      <mesh
        onClick={() => {
          handleCard("Cups-2");
        }}
        geometry={nodes.Cups_2.geometry}
        material={materials["Cups-2"]}
      />
      <mesh
        onClick={() => {
          handleCard("Cups-3");
        }}
        geometry={nodes.Cups_3.geometry}
        material={materials["Cups-3"]}
      />
      <mesh
        onClick={() => {
          handleCard("Cups-4");
        }}
        geometry={nodes.Cups_4.geometry}
        material={materials["Cups-4"]}
      />
      <mesh
        onClick={() => {
          handleCard("Cups-5");
        }}
        geometry={nodes.Cups_5.geometry}
        material={materials["Cups-5"]}
      />
      <mesh
        onClick={() => {
          handleCard("Cups-6");
        }}
        geometry={nodes.Cups_6.geometry}
        material={materials["Cups-6"]}
      />
      <mesh
        onClick={() => {
          handleCard("Cups-7");
        }}
        geometry={nodes.Cups_7.geometry}
        material={materials["Cups-7"]}
      />
      <mesh
        onClick={() => {
          handleCard("Cups-8");
        }}
        geometry={nodes.Cups_8.geometry}
        material={materials["Cups-8"]}
      />
      <mesh
        onClick={() => {
          handleCard("Cups-9");
        }}
        geometry={nodes.Cups_9.geometry}
        material={materials["Cups-9"]}
      />
      <mesh
        onClick={() => {
          handleCard("Cups-10");
        }}
        geometry={nodes.Cups_10.geometry}
        material={materials["Cups-10"]}
      />
      <mesh
        onClick={() => {
          handleCard("Swords-king");
        }}
        geometry={nodes.Swords_King.geometry}
        material={materials["Swords-king"]}
      />
      <mesh
        onClick={() => {
          handleCard("Swords-Queen");
        }}
        geometry={nodes.Swords_Queen.geometry}
        material={materials["Swords-Queen"]}
      />
      <mesh
        onClick={() => {
          handleCard("Swords-Knight");
        }}
        geometry={nodes.Swords_Knight.geometry}
        material={materials["Swords-Knight"]}
      />
      <mesh
        onClick={() => {
          handleCard("Swords-Page");
        }}
        geometry={nodes.Swords_Page.geometry}
        material={materials["Swords-Page"]}
      />
      <mesh
        onClick={() => {
          handleCard("Swords-Ace");
        }}
        geometry={nodes.Swords_Ace.geometry}
        material={materials["Swords-Ace"]}
      />
      <mesh
        onClick={() => {
          handleCard("Swords-2");
        }}
        geometry={nodes.Swords_2.geometry}
        material={materials["Swords-2"]}
      />
      <mesh
        onClick={() => {
          handleCard("Swords-3");
        }}
        geometry={nodes.Swords_3.geometry}
        material={materials["Swords-3"]}
      />
      <mesh
        onClick={() => {
          handleCard("Swords-4");
        }}
        geometry={nodes.Swords_4.geometry}
        material={materials["Swords-4"]}
      />
      <mesh
        onClick={() => {
          handleCard("Swords-5");
        }}
        geometry={nodes.Swords_5.geometry}
        material={materials["Swords-5"]}
      />
      <mesh
        onClick={() => {
          handleCard("Swords-6");
        }}
        geometry={nodes.Swords_6.geometry}
        material={materials["Swords-6"]}
      />
      <mesh
        onClick={() => {
          handleCard("Swords-7");
        }}
        geometry={nodes.Swords_7.geometry}
        material={materials["Swords-7"]}
      />
      <mesh
        onClick={() => {
          handleCard("Swords-8");
        }}
        geometry={nodes.Swords_8.geometry}
        material={materials["Swords-8"]}
      />
      <mesh
        onClick={() => {
          handleCard("Swords-9");
        }}
        geometry={nodes.Swords_9.geometry}
        material={materials["Swords-9"]}
      />
      <mesh
        onClick={() => {
          handleCard("Swords-10");
        }}
        geometry={nodes.Swords_10.geometry}
        material={materials["Swords-10"]}
      />
      <mesh
        onClick={() => {
          handleCard("Pentacles-King");
        }}
        geometry={nodes.Pentacles_King.geometry}
        material={materials["Pentacles-King"]}
      />
      <mesh
        onClick={() => {
          handleCard("Pentacles-Queen");
        }}
        geometry={nodes.Pentacles_Queen.geometry}
        material={materials["Pentacles-Queen"]}
      />
      <mesh
        onClick={() => {
          handleCard("Pentacles-Knight");
        }}
        geometry={nodes.Pentacles_Knight.geometry}
        material={materials["Pentacles-Knight"]}
      />
      <mesh
        onClick={() => {
          handleCard("Pentacles-Page");
        }}
        geometry={nodes.Pentacles_Page.geometry}
        material={materials["Pentacles-Page"]}
      />
      <mesh
        onClick={() => {
          handleCard("Pentacles-Ace");
        }}
        geometry={nodes.Pentacles_Ace.geometry}
        material={materials["Pentacles-Ace"]}
      />
      <mesh
        onClick={() => {
          handleCard("Pentacles-2");
        }}
        geometry={nodes.Pentacles_2.geometry}
        material={materials["Pentacles-2"]}
      />
      <mesh
        onClick={() => {
          handleCard("Pentacles-3");
        }}
        geometry={nodes.Pentacles_3.geometry}
        material={materials["Pentacles-3"]}
      />
      <mesh geometry={nodes.Pentacles_4.geometry} material={materials.Back} />
      <mesh
        onClick={() => {
          handleCard("Pentacles-4");
        }}
        geometry={nodes.Pentacles_4_1.geometry}
        material={materials["Pentacles-4"]}
      />
      <mesh geometry={nodes.Pentacles_4_2.geometry} material={materials.Side} />
      <mesh
        onClick={() => {
          handleCard("Pentacles-5");
        }}
        geometry={nodes.Pentacles_5.geometry}
        material={materials["Pentacles-5"]}
      />
      <mesh
        onClick={() => {
          handleCard("Pentacles-6");
        }}
        geometry={nodes.Pentacles_6.geometry}
        material={materials["Pentacles-6"]}
      />
      <mesh
        onClick={() => {
          handleCard("Pentacles-7");
        }}
        geometry={nodes.Pentacles_7.geometry}
        material={materials["Pentacles-7"]}
      />
      <mesh
        onClick={() => {
          handleCard("Pentacles-8");
        }}
        geometry={nodes.Pentacles_8.geometry}
        material={materials["Pentacles-8"]}
      />
      <mesh
        onClick={() => {
          handleCard("Pentacles-9");
        }}
        geometry={nodes.Pentacles_9.geometry}
        material={materials["Pentacles-9"]}
      />
      <mesh
        onClick={() => {
          handleCard("Pentacles-10");
        }}
        geometry={nodes.Pentacles_10.geometry}
        material={materials["Pentacles-10"]}
      />
      <instancedMesh
        args={[nodes.mesh_0.geometry, materials.Back, 200]}
        instanceMatrix={nodes.mesh_0.instanceMatrix}
      />
      {/* <instancedMesh
        args={[nodes.mesh_2.geometry, materials.Side, 199]}
        instanceMatrix={nodes.mesh_2.instanceMatrix}
      /> */}
    </group>
  );
}

useGLTF.preload("/tarot.gltf");
